//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 14-10-2015 04:38:23 PM
namespace PMS.ODataClient.PMS.Common
{
    /// <summary>
    /// There are no comments for BookDemandsSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("BookDemandsSingle")]
    public partial class BookDemandsSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<BookDemands>
    {
        /// <summary>
        /// Initialize a new BookDemandsSingle object.
        /// </summary>
        public BookDemandsSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new BookDemandsSingle object.
        /// </summary>
        public BookDemandsSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new BookDemandsSingle object.
        /// </summary>
        public BookDemandsSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<BookDemands> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Member in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Member")]
        public global::PMS.ODataClient.PMS.Common.MemberSingle Member
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Member == null))
                {
                    this._Member = new global::PMS.ODataClient.PMS.Common.MemberSingle(this.Context, GetPath("Member"));
                }
                return this._Member;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::PMS.ODataClient.PMS.Common.MemberSingle _Member;
        /// <summary>
        /// There are no comments for Publisher in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Publisher")]
        public global::PMS.ODataClient.PMS.Common.PublisherSingle Publisher
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Publisher == null))
                {
                    this._Publisher = new global::PMS.ODataClient.PMS.Common.PublisherSingle(this.Context, GetPath("Publisher"));
                }
                return this._Publisher;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::PMS.ODataClient.PMS.Common.PublisherSingle _Publisher;
    }
    /// <summary>
    /// There are no comments for BookDemands in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("BookDemands")]
    public partial class BookDemands : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new BookDemands object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="quantity">Initial value of Quantity.</param>
        /// <param name="demandDate">Initial value of DemandDate.</param>
        /// <param name="publishYear">Initial value of PublishYear.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static BookDemands CreateBookDemands(global::System.Guid ID, int quantity, global::System.DateTimeOffset demandDate, int publishYear)
        {
            BookDemands bookDemands = new BookDemands();
            bookDemands.Id = ID;
            bookDemands.Quantity = quantity;
            bookDemands.DemandDate = demandDate;
            bookDemands.PublishYear = publishYear;
            return bookDemands;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property MemberId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MemberId")]
        public global::System.Nullable<global::System.Guid> MemberId
        {
            get
            {
                return this._MemberId;
            }
            set
            {
                this.OnMemberIdChanging(value);
                this._MemberId = value;
                this.OnMemberIdChanged();
                this.OnPropertyChanged("MemberId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.Guid> _MemberId;
        partial void OnMemberIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnMemberIdChanged();
        /// <summary>
        /// There are no comments for Property PublisherId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PublisherId")]
        public global::System.Nullable<global::System.Guid> PublisherId
        {
            get
            {
                return this._PublisherId;
            }
            set
            {
                this.OnPublisherIdChanging(value);
                this._PublisherId = value;
                this.OnPublisherIdChanged();
                this.OnPropertyChanged("PublisherId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.Guid> _PublisherId;
        partial void OnPublisherIdChanging(global::System.Nullable<global::System.Guid> value);
        partial void OnPublisherIdChanged();
        /// <summary>
        /// There are no comments for Property BookId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BookId")]
        public string BookId
        {
            get
            {
                return this._BookId;
            }
            set
            {
                this.OnBookIdChanging(value);
                this._BookId = value;
                this.OnBookIdChanged();
                this.OnPropertyChanged("BookId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _BookId;
        partial void OnBookIdChanging(string value);
        partial void OnBookIdChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Quantity")]
        public int Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this._Quantity = value;
                this.OnQuantityChanged();
                this.OnPropertyChanged("Quantity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Quantity;
        partial void OnQuantityChanging(int value);
        partial void OnQuantityChanged();
        /// <summary>
        /// There are no comments for Property DemandDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DemandDate")]
        public global::System.DateTimeOffset DemandDate
        {
            get
            {
                return this._DemandDate;
            }
            set
            {
                this.OnDemandDateChanging(value);
                this._DemandDate = value;
                this.OnDemandDateChanged();
                this.OnPropertyChanged("DemandDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.DateTimeOffset _DemandDate;
        partial void OnDemandDateChanging(global::System.DateTimeOffset value);
        partial void OnDemandDateChanged();
        /// <summary>
        /// There are no comments for Property BookName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BookName")]
        public string BookName
        {
            get
            {
                return this._BookName;
            }
            set
            {
                this.OnBookNameChanging(value);
                this._BookName = value;
                this.OnBookNameChanged();
                this.OnPropertyChanged("BookName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _BookName;
        partial void OnBookNameChanging(string value);
        partial void OnBookNameChanged();
        /// <summary>
        /// There are no comments for Property PublishYear in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PublishYear")]
        public int PublishYear
        {
            get
            {
                return this._PublishYear;
            }
            set
            {
                this.OnPublishYearChanging(value);
                this._PublishYear = value;
                this.OnPublishYearChanged();
                this.OnPropertyChanged("PublishYear");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _PublishYear;
        partial void OnPublishYearChanging(int value);
        partial void OnPublishYearChanged();
        /// <summary>
        /// There are no comments for Property Member in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Member")]
        public global::PMS.ODataClient.PMS.Common.Member Member
        {
            get
            {
                return this._Member;
            }
            set
            {
                this.OnMemberChanging(value);
                this._Member = value;
                this.OnMemberChanged();
                this.OnPropertyChanged("Member");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::PMS.ODataClient.PMS.Common.Member _Member;
        partial void OnMemberChanging(global::PMS.ODataClient.PMS.Common.Member value);
        partial void OnMemberChanged();
        /// <summary>
        /// There are no comments for Property Publisher in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Publisher")]
        public global::PMS.ODataClient.PMS.Common.Publisher Publisher
        {
            get
            {
                return this._Publisher;
            }
            set
            {
                this.OnPublisherChanging(value);
                this._Publisher = value;
                this.OnPublisherChanged();
                this.OnPropertyChanged("Publisher");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::PMS.ODataClient.PMS.Common.Publisher _Publisher;
        partial void OnPublisherChanging(global::PMS.ODataClient.PMS.Common.Publisher value);
        partial void OnPublisherChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for MemberSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("MemberSingle")]
    public partial class MemberSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Member>
    {
        /// <summary>
        /// Initialize a new MemberSingle object.
        /// </summary>
        public MemberSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new MemberSingle object.
        /// </summary>
        public MemberSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new MemberSingle object.
        /// </summary>
        public MemberSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Member> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for BookDemands in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BookDemands")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.BookDemands> BookDemands
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._BookDemands == null))
                {
                    this._BookDemands = Context.CreateQuery<global::PMS.ODataClient.PMS.Common.BookDemands>(GetPath("BookDemands"));
                }
                return this._BookDemands;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.BookDemands> _BookDemands;
    }
    /// <summary>
    /// There are no comments for Member in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Member")]
    public partial class Member : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Member object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Member CreateMember(global::System.Guid ID)
        {
            Member member = new Member();
            member.Id = ID;
            return member;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FirstName")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastName")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserName")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
                this.OnPropertyChanged("UserName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Password")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property University in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("University")]
        public string University
        {
            get
            {
                return this._University;
            }
            set
            {
                this.OnUniversityChanging(value);
                this._University = value;
                this.OnUniversityChanged();
                this.OnPropertyChanged("University");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _University;
        partial void OnUniversityChanging(string value);
        partial void OnUniversityChanged();
        /// <summary>
        /// There are no comments for Property EmailAddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EmailAddress")]
        public string EmailAddress
        {
            get
            {
                return this._EmailAddress;
            }
            set
            {
                this.OnEmailAddressChanging(value);
                this._EmailAddress = value;
                this.OnEmailAddressChanged();
                this.OnPropertyChanged("EmailAddress");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _EmailAddress;
        partial void OnEmailAddressChanging(string value);
        partial void OnEmailAddressChanged();
        /// <summary>
        /// There are no comments for Property BookDemands in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BookDemands")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::PMS.ODataClient.PMS.Common.BookDemands> BookDemands
        {
            get
            {
                return this._BookDemands;
            }
            set
            {
                this.OnBookDemandsChanging(value);
                this._BookDemands = value;
                this.OnBookDemandsChanged();
                this.OnPropertyChanged("BookDemands");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::PMS.ODataClient.PMS.Common.BookDemands> _BookDemands = new global::Microsoft.OData.Client.DataServiceCollection<global::PMS.ODataClient.PMS.Common.BookDemands>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnBookDemandsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::PMS.ODataClient.PMS.Common.BookDemands> value);
        partial void OnBookDemandsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PublisherSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("PublisherSingle")]
    public partial class PublisherSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Publisher>
    {
        /// <summary>
        /// Initialize a new PublisherSingle object.
        /// </summary>
        public PublisherSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PublisherSingle object.
        /// </summary>
        public PublisherSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PublisherSingle object.
        /// </summary>
        public PublisherSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Publisher> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for BookDemands in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BookDemands")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.BookDemands> BookDemands
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._BookDemands == null))
                {
                    this._BookDemands = Context.CreateQuery<global::PMS.ODataClient.PMS.Common.BookDemands>(GetPath("BookDemands"));
                }
                return this._BookDemands;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.BookDemands> _BookDemands;
    }
    /// <summary>
    /// There are no comments for Publisher in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Publisher")]
    public partial class Publisher : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Publisher object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="postCode">Initial value of PostCode.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Publisher CreatePublisher(global::System.Guid ID, int postCode)
        {
            Publisher publisher = new Publisher();
            publisher.Id = ID;
            publisher.PostCode = postCode;
            return publisher;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Address")]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this.OnAddressChanged();
                this.OnPropertyChanged("Address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("City")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
                this.OnPropertyChanged("City");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property PostCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PostCode")]
        public int PostCode
        {
            get
            {
                return this._PostCode;
            }
            set
            {
                this.OnPostCodeChanging(value);
                this._PostCode = value;
                this.OnPostCodeChanged();
                this.OnPropertyChanged("PostCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _PostCode;
        partial void OnPostCodeChanging(int value);
        partial void OnPostCodeChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Phone")]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this._Phone = value;
                this.OnPhoneChanged();
                this.OnPropertyChanged("Phone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Email")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property BookDemands in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BookDemands")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::PMS.ODataClient.PMS.Common.BookDemands> BookDemands
        {
            get
            {
                return this._BookDemands;
            }
            set
            {
                this.OnBookDemandsChanging(value);
                this._BookDemands = value;
                this.OnBookDemandsChanged();
                this.OnPropertyChanged("BookDemands");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::PMS.ODataClient.PMS.Common.BookDemands> _BookDemands = new global::Microsoft.OData.Client.DataServiceCollection<global::PMS.ODataClient.PMS.Common.BookDemands>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnBookDemandsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::PMS.ODataClient.PMS.Common.BookDemands> value);
        partial void OnBookDemandsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::PMS.ODataClient.PMS.Common.BookDemands as global::PMS.ODataClient.PMS.Common.BookDemandsSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::PMS.ODataClient.PMS.Common.BookDemandsSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.BookDemands> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::PMS.ODataClient.PMS.Common.BookDemandsSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::PMS.ODataClient.PMS.Common.BookDemands as global::PMS.ODataClient.PMS.Common.BookDemandsSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::PMS.ODataClient.PMS.Common.BookDemandsSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.BookDemands> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::PMS.ODataClient.PMS.Common.BookDemandsSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::PMS.ODataClient.PMS.Common.Member as global::PMS.ODataClient.PMS.Common.MemberSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::PMS.ODataClient.PMS.Common.MemberSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.Member> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::PMS.ODataClient.PMS.Common.MemberSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::PMS.ODataClient.PMS.Common.Member as global::PMS.ODataClient.PMS.Common.MemberSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::PMS.ODataClient.PMS.Common.MemberSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.Member> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::PMS.ODataClient.PMS.Common.MemberSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::PMS.ODataClient.PMS.Common.Publisher as global::PMS.ODataClient.PMS.Common.PublisherSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::PMS.ODataClient.PMS.Common.PublisherSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.Publisher> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::PMS.ODataClient.PMS.Common.PublisherSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::PMS.ODataClient.PMS.Common.Publisher as global::PMS.ODataClient.PMS.Common.PublisherSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::PMS.ODataClient.PMS.Common.PublisherSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.Publisher> source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::PMS.ODataClient.PMS.Common.PublisherSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace PMS.ODataClient.ODataService
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "ODataService", "PMS.ODataClient.ODataService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "PMS.Common", "PMS.ODataClient.PMS.Common");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("PMS.ODataClient.ODataService", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("ODataService.", originalNameAttribute.OriginalName);
                }
                return string.Concat("ODataService.", clientType.Name);
            }
            if (clientType.Namespace.Equals("PMS.ODataClient.PMS.Common", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("PMS.Common.", originalNameAttribute.OriginalName);
                }
                return string.Concat("PMS.Common.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for BookDemands in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BookDemands")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.BookDemands> BookDemands
        {
            get
            {
                if ((this._BookDemands == null))
                {
                    this._BookDemands = base.CreateQuery<global::PMS.ODataClient.PMS.Common.BookDemands>("BookDemands");
                }
                return this._BookDemands;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.BookDemands> _BookDemands;
        /// <summary>
        /// There are no comments for Members in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Members")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.Member> Members
        {
            get
            {
                if ((this._Members == null))
                {
                    this._Members = base.CreateQuery<global::PMS.ODataClient.PMS.Common.Member>("Members");
                }
                return this._Members;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.Member> _Members;
        /// <summary>
        /// There are no comments for Publishers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Publishers")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.Publisher> Publishers
        {
            get
            {
                if ((this._Publishers == null))
                {
                    this._Publishers = base.CreateQuery<global::PMS.ODataClient.PMS.Common.Publisher>("Publishers");
                }
                return this._Publishers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.Publisher> _Publishers;
        /// <summary>
        /// There are no comments for BookDemands in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToBookDemands(global::PMS.ODataClient.PMS.Common.BookDemands bookDemands)
        {
            base.AddObject("BookDemands", bookDemands);
        }
        /// <summary>
        /// There are no comments for Members in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToMembers(global::PMS.ODataClient.PMS.Common.Member member)
        {
            base.AddObject("Members", member);
        }
        /// <summary>
        /// There are no comments for Publishers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToPublishers(global::PMS.ODataClient.PMS.Common.Publisher publisher)
        {
            base.AddObject("Publishers", publisher);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""PMS.Common"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""BookDemands"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""MemberId"" Type=""Edm.Guid"" />
        <Property Name=""PublisherId"" Type=""Edm.Guid"" />
        <Property Name=""BookId"" Type=""Edm.String"" />
        <Property Name=""Quantity"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""DemandDate"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""BookName"" Type=""Edm.String"" />
        <Property Name=""PublishYear"" Type=""Edm.Int32"" Nullable=""false"" />
        <NavigationProperty Name=""Member"" Type=""PMS.Common.Member"">
          <ReferentialConstraint Property=""MemberId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
        <NavigationProperty Name=""Publisher"" Type=""PMS.Common.Publisher"">
          <ReferentialConstraint Property=""PublisherId"" ReferencedProperty=""Id"" />
        </NavigationProperty>
      </EntityType>
      <EntityType Name=""Member"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""FirstName"" Type=""Edm.String"" />
        <Property Name=""LastName"" Type=""Edm.String"" />
        <Property Name=""UserName"" Type=""Edm.String"" />
        <Property Name=""Password"" Type=""Edm.String"" />
        <Property Name=""University"" Type=""Edm.String"" />
        <Property Name=""EmailAddress"" Type=""Edm.String"" />
        <NavigationProperty Name=""BookDemands"" Type=""Collection(PMS.Common.BookDemands)"" />
      </EntityType>
      <EntityType Name=""Publisher"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Address"" Type=""Edm.String"" />
        <Property Name=""City"" Type=""Edm.String"" />
        <Property Name=""PostCode"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Phone"" Type=""Edm.String"" />
        <Property Name=""Email"" Type=""Edm.String"" />
        <NavigationProperty Name=""BookDemands"" Type=""Collection(PMS.Common.BookDemands)"" />
      </EntityType>
    </Schema>
    <Schema Namespace=""ODataService"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <Action Name=""CancelDemand"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""PMS.Common.BookDemands"" />
        <Parameter Name=""Reason"" Type=""Edm.String"" Unicode=""false"" />
      </Action>
      <Function Name=""MostWanted"" IsBound=""true"">
        <Parameter Name=""bindingParameter"" Type=""Collection(PMS.Common.BookDemands)"" />
        <ReturnType Type=""Edm.String"" Unicode=""false"" />
      </Function>
      <Function Name=""GetGoldRate"">
        <Parameter Name=""Country"" Type=""Edm.String"" Unicode=""false"" />
        <ReturnType Type=""Edm.Double"" Nullable=""false"" />
      </Function>
      <EntityContainer Name=""Container"">
        <EntitySet Name=""BookDemands"" EntityType=""PMS.Common.BookDemands"">
          <NavigationPropertyBinding Path=""Member"" Target=""Members"" />
          <NavigationPropertyBinding Path=""Publisher"" Target=""Publishers"" />
        </EntitySet>
        <EntitySet Name=""Members"" EntityType=""PMS.Common.Member"">
          <NavigationPropertyBinding Path=""BookDemands"" Target=""BookDemands"" />
        </EntitySet>
        <EntitySet Name=""Publishers"" EntityType=""PMS.Common.Publisher"">
          <NavigationPropertyBinding Path=""BookDemands"" Target=""BookDemands"" />
        </EntitySet>
        <FunctionImport Name=""GetGoldRate"" Function=""ODataService.GetGoldRate"" IncludeInServiceDocument=""true"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
        /// <summary>
        /// There are no comments for GetGoldRate in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("GetGoldRate")]
        public global::Microsoft.OData.Client.DataServiceQuerySingle<double> GetGoldRate(string Country)
        {
            return this.CreateFunctionQuerySingle<double>("", "GetGoldRate", false, new global::Microsoft.OData.Client.UriOperationParameter("Country", Country));
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// There are no comments for MostWanted in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("MostWanted")]
        public static global::Microsoft.OData.Client.DataServiceQuerySingle<string> MostWanted(this global::Microsoft.OData.Client.DataServiceQuery<global::PMS.ODataClient.PMS.Common.BookDemands> source)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return source.CreateFunctionQuerySingle<string>("ODataService.MostWanted", false);
        }
        /// <summary>
        /// There are no comments for CancelDemand in the schema.
        /// </summary>
        [global::Microsoft.OData.Client.OriginalNameAttribute("CancelDemand")]
        public static global::Microsoft.OData.Client.DataServiceActionQuery CancelDemand(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::PMS.ODataClient.PMS.Common.BookDemands> source, string Reason)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuery(source.Context, source.AppendRequestUri("ODataService.CancelDemand"), new global::Microsoft.OData.Client.BodyOperationParameter("Reason", Reason));
        }
    }
}
